micronaut:
  application:
    name: TMDB
  server:
    cors:
      enabled: true
datasources:
  default:
    url: jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2
tmdb:
  api-key: fd6bbf5b30d16dbe410178c8f6c2b0a8
netty:
  default:
    allocator:
      max-order: 3

